### 查询课程信息
POST {{gateway_host}}/content/course/list?pageNo=1&pageSize=10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE3NDgwNzQzMzIsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6IjdiZjU1NWJiLTk0ODAtNGMxNi1iYTAyLTQyYTRmNzFhZGM1YSIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.LFAiRo0YGrEakIWPpgvzUEbHclkbjDmsrJTcXUJwIn4

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus": ""
}

<> 2025-05-05T202802.200.json
<> 2025-05-05T202739.404.html

### 查询分类信息
GET {{content_host}}/content/course-category/tree-nodes

### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201001",
  "price": 100,
  "originalPrice":1000,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "",
  "pic": "",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "",
  "grade": "204001",
  "description": "java网络编程java网络编程java网络编程java网络编程"
}

### 课程计划查询
GET {{content_host}}/content/teachplan/117/tree-nodes
Content-Type: application/json

### 删除课程计划
DELETE {{content_host}}/content/teachplan/43
Content-Type: application/json

### 查询课程信息
GET {{gateway_host}}/content/course/117
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjb21wYW55SWRcIjpcIjEyMzIxNDE0MjVcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjItMDktMjhUMDg6MzI6MDNcIixcImlkXCI6XCI1MlwiLFwibmFtZVwiOlwiTeiAgeW4iFwiLFwicGFzc3dvcmRcIjpcIiQyYSQxMCQwcHQ3V2xmVGJuUERUY1d0cC8uMk11NUNUWHZvaG5OUWhSNjI4cXE0Um9LU2MwZEdBZEVnbVwiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIlwiLFwidXNlcm5hbWVcIjpcInQxXCIsXCJ1dHlwZVwiOlwiMTAxMDAyXCJ9Iiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTc0ODA3ODkyOSwiYXV0aG9yaXRpZXMiOlsidGVzdCJdLCJqdGkiOiI3YzdjN2RhMy1hYzA3LTRlMGEtOTUxNC02NDE5NDBhZjcxYTgiLCJjbGllbnRfaWQiOiJYY1dlYkFwcCJ9.AdJtkcdmd085EmdYwcRpzI41ciMvF5dZrNmbZB2jFd8
